GET http://localhost:3000/api/diary/

### obtener todo
GET http://localhost:3000/api/diary/1


### Crear
POST http://localhost:3000/api/diary/
Content-Type: application/json

{
    "date": "2021-01-01",
    "weather": "sunny",
    "visibility":"good",
    "comment": "good day"
}
